/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamic_model_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* F_Rprediction_horizon4:(x[4],u)->(x_next[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.0000000000000001e-01;
  a2=arg[0]? arg[0][2] : 0;
  a3=2.;
  a4=3.5600000000000000e-02;
  a5=arg[0]? arg[0][1] : 0;
  a6=sin(a5);
  a7=(a4*a6);
  a8=arg[0]? arg[0][3] : 0;
  a9=casadi_sq(a8);
  a7=(a7*a9);
  a9=8.7309000000000003e-01;
  a10=(a9*a6);
  a11=cos(a5);
  a10=(a10*a11);
  a7=(a7+a10);
  a10=arg[1]? arg[1][0] : 0;
  a7=(a7+a10);
  a12=1.2300000000000000e-01;
  a13=8.8999999999999996e-02;
  a14=casadi_sq(a6);
  a14=(a13*a14);
  a14=(a12+a14);
  a7=(a7/a14);
  a15=(a1*a7);
  a15=(a15/a3);
  a15=(a2+a15);
  a15=(a3*a15);
  a15=(a2+a15);
  a16=(a1*a8);
  a16=(a16/a3);
  a16=(a5+a16);
  a17=sin(a16);
  a18=(a4*a17);
  a19=(a4*a6);
  a19=(a19*a11);
  a20=casadi_sq(a8);
  a19=(a19*a20);
  a20=2.0797200000000000e+00;
  a6=(a20*a6);
  a19=(a19+a6);
  a11=(a10*a11);
  a19=(a19+a11);
  a11=4.0000000000000002e-01;
  a14=(a11*a14);
  a19=(a19/a14);
  a14=(a1*a19);
  a14=(a14/a3);
  a14=(a8+a14);
  a6=casadi_sq(a14);
  a18=(a18*a6);
  a6=(a9*a17);
  a16=cos(a16);
  a6=(a6*a16);
  a18=(a18+a6);
  a18=(a18+a10);
  a6=casadi_sq(a17);
  a6=(a13*a6);
  a6=(a12+a6);
  a18=(a18/a6);
  a21=(a1*a18);
  a21=(a21/a3);
  a21=(a2+a21);
  a21=(a3*a21);
  a15=(a15+a21);
  a21=(a1*a14);
  a21=(a21/a3);
  a21=(a5+a21);
  a22=sin(a21);
  a23=(a4*a22);
  a24=(a4*a17);
  a24=(a24*a16);
  a25=casadi_sq(a14);
  a24=(a24*a25);
  a17=(a20*a17);
  a24=(a24+a17);
  a16=(a10*a16);
  a24=(a24+a16);
  a6=(a11*a6);
  a24=(a24/a6);
  a6=(a1*a24);
  a6=(a6/a3);
  a6=(a8+a6);
  a16=casadi_sq(a6);
  a23=(a23*a16);
  a16=(a9*a22);
  a21=cos(a21);
  a16=(a16*a21);
  a23=(a23+a16);
  a23=(a23+a10);
  a16=casadi_sq(a22);
  a16=(a13*a16);
  a16=(a12+a16);
  a23=(a23/a16);
  a17=(a1*a23);
  a17=(a2+a17);
  a15=(a15+a17);
  a15=(a1*a15);
  a17=6.;
  a15=(a15/a17);
  a0=(a0+a15);
  if (res[0]!=0) res[0][0]=a0;
  a14=(a3*a14);
  a14=(a8+a14);
  a0=(a3*a6);
  a14=(a14+a0);
  a0=(a4*a22);
  a0=(a0*a21);
  a15=casadi_sq(a6);
  a0=(a0*a15);
  a22=(a20*a22);
  a0=(a0+a22);
  a21=(a10*a21);
  a0=(a0+a21);
  a16=(a11*a16);
  a0=(a0/a16);
  a16=(a1*a0);
  a16=(a8+a16);
  a14=(a14+a16);
  a14=(a1*a14);
  a14=(a14/a17);
  a14=(a5+a14);
  if (res[0]!=0) res[0][1]=a14;
  a18=(a3*a18);
  a7=(a7+a18);
  a23=(a3*a23);
  a7=(a7+a23);
  a6=(a1*a6);
  a5=(a5+a6);
  a6=sin(a5);
  a23=(a4*a6);
  a18=casadi_sq(a16);
  a23=(a23*a18);
  a9=(a9*a6);
  a5=cos(a5);
  a9=(a9*a5);
  a23=(a23+a9);
  a23=(a23+a10);
  a9=casadi_sq(a6);
  a13=(a13*a9);
  a12=(a12+a13);
  a23=(a23/a12);
  a7=(a7+a23);
  a7=(a1*a7);
  a7=(a7/a17);
  a2=(a2+a7);
  if (res[0]!=0) res[0][2]=a2;
  a24=(a3*a24);
  a19=(a19+a24);
  a3=(a3*a0);
  a19=(a19+a3);
  a4=(a4*a6);
  a4=(a4*a5);
  a16=casadi_sq(a16);
  a4=(a4*a16);
  a20=(a20*a6);
  a4=(a4+a20);
  a10=(a10*a5);
  a4=(a4+a10);
  a11=(a11*a12);
  a4=(a4/a11);
  a19=(a19+a4);
  a1=(a1*a19);
  a1=(a1/a17);
  a8=(a8+a1);
  if (res[0]!=0) res[0][3]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_Rprediction_horizon4_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_Rprediction_horizon4_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_Rprediction_horizon4_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_Rprediction_horizon4_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_Rprediction_horizon4_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int F_Rprediction_horizon4_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_Rprediction_horizon4_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_Rprediction_horizon4_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_Rprediction_horizon4_name_out(casadi_int i) {
  switch (i) {
    case 0: return "x_next";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_Rprediction_horizon4_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_Rprediction_horizon4_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_Rprediction_horizon4_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
